[database]
db_name = "PDF_Skimmer"

[model]
providers = ["gemini", "openai", "deepseek", "qwen"]
gemini_model_name = "gemini-2.0-flash-exp"
openai_model_name = "o3-mini"
deepseek_model_name = "deepseek-chat"
qwen_model_name = "qwen-max"

[prompts]
analysis = '''Analyze the academic journal article at the LINK user provides.
Generate a structured report that provides a clear and concise overview of the article. The report should cover the following key aspects, presented in a well-organized and easily digestible format.

**Report Structure:**

1.  **Core Research Question/Problem (core_question):**
    *   Clearly state the central research question or problem the authors are trying to address in this article.
    *   What gap in knowledge are they aiming to fill?
    *   What specific issue are they investigating?
    *   Explain *why* this research question or problem is important.

2.  **Background Knowledge and Context (introduction):**
    *   IMPORTANT: This section is not a summary, it should be a detailed analysis of the background knowledge and context.
    *   Inspect thoroughly the introduction section.
          *   Explain all the relevant theories, previous research, or established concepts introduced in the article that are helpful for comprehending the current study.
          *   Follow the author's logical flow, but you can reorganize the connections between the introduced concepts.
    *   Explain the debates concerning the research question.
          *   What are the main arguments for and against the research question?
          *   What are the arguments that the authors defend, and what are their rationales?

3.  **Author's Approach and Methodology (methodology):**
    *   Describe the author's strategy or methodology to address the research question.
    *   Explain the details of the methods, techniques, or data used by the authors.
    *   If there is a unique characteristic of this study in terms of methodology, emphasize and explain it.

4.  **Key Results and Findings (results):**
    *   Present the important results and findings of the study one by one.
    *   Highlight the significant outcomes and discoveries.
    *   Use quantifiable results or specific findings whenever possible.

5.  **Implications and Discussion (discussion):**
    *   Discuss the implications of the results. What do these findings mean in a broader context?
    *   How does the author interpret their results?
    *   How does this result compare to the previous researches?
    *   How do the results contribute to the existing knowledge in the field?

6.  **Limitations and Future Directions (limitations):**
    *   Identify and explain the limitations of the study as acknowledged by the authors or evident from the methodology.
    *   What was the authors strategy to overcome the limitations?
    *   How did the authors defend their results despite these limitations.

Ensure accurate representation of the article's content and avoid making assumptions or adding external information

Output the result in JSON format with the following keys:
- core_question
- introduction
- methodology
- results
- discussion
- limitations

LINK:{LINK}
'''

chatbot = '''You are an AI assistant helping to answer questions about the research paper provided at the LINK.

{LINK}'''

[display]
tab_names = ["Core Question", "Introduction", "Methodology", "Results", "Discussion", "Limitations"]
tab_icons = ["💡", "📄", "🔍", "📊", "📊", "💡"]

[directories]
base_url = "http://anselmjeong.synology.me:8091/share/GXzzOcfK"
base_dir = "/Volumes/LIBRARY/Articles/"


[home_directory]
base_dir = "/Volumes/AnselmJeong.ddns.net/LIBRARY/Articles"
